//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attatchment_Relation
    {
        public int ID { get; set; }
        public Nullable<int> TableRowId { get; set; }
        public Nullable<int> FormId { get; set; }
        public Nullable<int> FileID { get; set; }
    }
}
