//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Accounts
    {
        public int ID { get; set; }
        public string Acc_Name { get; set; }
        public string Acc_Number { get; set; }
        public string Acc_Title { get; set; }
        public string IBAN { get; set; }
        public string Acc_Currency { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public string Swift_Code { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<int> GL_Mapping { get; set; }
        public string Flex_1 { get; set; }
        public string Flex_2 { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public Nullable<int> SecurityGroupId { get; set; }
    }
}
