//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashreceivedForm
    {
        public int ID { get; set; }
        public string Receipt_Number { get; set; }
        public Nullable<System.DateTime> Recived_Date { get; set; }
        public string Description { get; set; }
        public string Recived_Form { get; set; }
        public string Paid_By { get; set; }
        public string Profession { get; set; }
        public string Recived_By { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public string Security_Group_ID { get; set; }
        public string Flex_1 { get; set; }
        public string Flex_2 { get; set; }
        public string Atrib_1 { get; set; }
        public string Atrib_2 { get; set; }
        public string Atrib_3 { get; set; }
        public string Atrib_4 { get; set; }
        public string Atrib_5 { get; set; }
        public string Atrib_6 { get; set; }
    }
}
