//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COA_Segments
    {
        public int ID { get; set; }
        public string Segment { get; set; }
        public string Segment_Value { get; set; }
        public string Name { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string Use { get; set; }
        public string Parent_C_CODE { get; set; }
        public string Control_Account { get; set; }
        public string Flex_1 { get; set; }
        public string Flex_2 { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_ON { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
    }
}
