//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MIS_DBEntities : DbContext
    {
        public MIS_DBEntities()
            : base("name=MIS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking_Confirm> Booking_Confirm { get; set; }
        public virtual DbSet<PaymentInstallment> PaymentInstallments { get; set; }
        public virtual DbSet<PaymentMilestoneDetail> PaymentMilestoneDetails { get; set; }
        public virtual DbSet<PaymentMilestone> PaymentMilestones { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectDetail> ProjectDetails { get; set; }
        public virtual DbSet<Property_def> Property_def { get; set; }
        public virtual DbSet<PropertySale> PropertySales { get; set; }
        public virtual DbSet<Prospect> Prospects { get; set; }
        public virtual DbSet<Rebate_Details> Rebate_Details { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<SaleInstallment> SaleInstallments { get; set; }
        public virtual DbSet<TempTableForInstallment> TempTableForInstallments { get; set; }
        public virtual DbSet<Booking_Payments> Booking_Payments { get; set; }
        public virtual DbSet<Lookup_List> Lookup_List { get; set; }
    }
}
