//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_Headers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GL_Headers()
        {
            this.GL_Lines = new HashSet<GL_Lines>();
        }
    
        public int H_ID { get; set; }
        public System.DateTime J_Date { get; set; }
        public Nullable<System.DateTime> Doc_Date { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string Source { get; set; }
        public Nullable<int> Source_Tran_Id { get; set; }
        public string Pay_Mode { get; set; }
        public string Pay_Bank { get; set; }
        public string Pay_To { get; set; }
        public string Pay_Company { get; set; }
        public string Pay_Project { get; set; }
        public string Pay_Location { get; set; }
        public string Dep_Mode { get; set; }
        public string Dep_Bank { get; set; }
        public string Dep_By { get; set; }
        public string Dep_Company { get; set; }
        public string Dep_Project { get; set; }
        public string Dep_Location { get; set; }
        public string Trans_Status { get; set; }
        public string Posted_date { get; set; }
        public string Flex_1 { get; set; }
        public string Flex_2 { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public string Ref_Field { get; set; }
        public Nullable<int> SecurityGroupId { get; set; }
        public string Payment_Mode { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string PayeeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Lines> GL_Lines { get; set; }
    }
}
