//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup_Values
    {
        public int Value_ID { get; set; }
        public int Ref_ID { get; set; }
        public string Value_Description { get; set; }
        public Nullable<int> Value_orderNo { get; set; }
        public Nullable<bool> Value_Status { get; set; }
        public Nullable<System.DateTime> Created_ON { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_ON { get; set; }
        public string Updated_By { get; set; }
    
        public virtual Lookup_List Lookup_List { get; set; }
    }
}
