//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MIS_DBEntities1 : DbContext
    {
        public MIS_DBEntities1()
            : base("name=MIS_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingConfirm> BookingConfirms { get; set; }
        public virtual DbSet<BookingPayment> BookingPayments { get; set; }
        public virtual DbSet<Delivery_Sheet> Delivery_Sheet { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Lookup_List> Lookup_List { get; set; }
        public virtual DbSet<Lookup_Values> Lookup_Values { get; set; }
        public virtual DbSet<Payment_Delivery> Payment_Delivery { get; set; }
        public virtual DbSet<PaymentInstallment> PaymentInstallments { get; set; }
        public virtual DbSet<PaymentMilestoneDetail> PaymentMilestoneDetails { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectDetail> ProjectDetails { get; set; }
        public virtual DbSet<PropertyDef> PropertyDefs { get; set; }
        public virtual DbSet<PropertySale> PropertySales { get; set; }
        public virtual DbSet<Prospect> Prospects { get; set; }
        public virtual DbSet<Rebate_Details> Rebate_Details { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<SaleInstallment> SaleInstallments { get; set; }
        public virtual DbSet<Society_Slip> Society_Slip { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<COA_Combinations> COA_Combinations { get; set; }
        public virtual DbSet<COA_Segments> COA_Segments { get; set; }
        public virtual DbSet<TempTableForInstallment> TempTableForInstallments { get; set; }
        public virtual DbSet<PaymentMilestone> PaymentMilestones { get; set; }
        public virtual DbSet<Bank_Accounts> Bank_Accounts { get; set; }
        public virtual DbSet<GL_Balances> GL_Balances { get; set; }
        public virtual DbSet<GL_Headers> GL_Headers { get; set; }
        public virtual DbSet<GL_Lines> GL_Lines { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<PrivilegesToRole> PrivilegesToRoles { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolesToUser> RolesToUsers { get; set; }
        public virtual DbSet<SecurityGroup> SecurityGroups { get; set; }
        public virtual DbSet<Booking_Entries> Booking_Entries { get; set; }
        public virtual DbSet<Project_Entries> Project_Entries { get; set; }
    }
}
