//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMilestoneDetail
    {
        public int Id { get; set; }
        public string Milestones { get; set; }
        public Nullable<double> Percentage { get; set; }
        public string Frequency { get; set; }
        public int parentId { get; set; }
        public Nullable<int> InstallmentNumber { get; set; }
    
        public virtual PaymentMilestone PaymentMilestone { get; set; }
    }
}
