//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMilestone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentMilestone()
        {
            this.PaymentMilestoneDetails = new HashSet<PaymentMilestoneDetail>();
        }
    
        public int Id { get; set; }
        public string PaymentScheduleCode { get; set; }
        public Nullable<int> projectId { get; set; }
        public string projectName { get; set; }
        public Nullable<int> GracePeriodDays { get; set; }
        public Nullable<int> Tax { get; set; }
        public string LateFeePercent { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentMilestoneDetail> PaymentMilestoneDetails { get; set; }
    }
}
