//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectDetails = new HashSet<ProjectDetail>();
        }
    
        public int Id { get; set; }
        public string projectCode { get; set; }
        public string projectName { get; set; }
        public string projectType { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public Nullable<double> totalArea { get; set; }
        public string unit { get; set; }
        public string noc { get; set; }
        public string projectCurrency { get; set; }
        public string location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDetail> ProjectDetails { get; set; }
    }
}
