//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetail
    {
        public int Id { get; set; }
        public string unitNumber { get; set; }
        public string unitType { get; set; }
        public Nullable<int> childArea { get; set; }
        public string childStatus { get; set; }
        public Nullable<int> building { get; set; }
        public Nullable<int> floor { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public string childDescription { get; set; }
        public string otherFeatures { get; set; }
        public Nullable<int> projectId { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
