//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospect
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string cnic { get; set; }
        public string prospectType { get; set; }
        public string mobile { get; set; }
        public string profession { get; set; }
        public string knowUs { get; set; }
        public string address { get; set; }
        public Nullable<int> city { get; set; }
        public string projectId { get; set; }
        public Nullable<int> employeeId { get; set; }
        public string description { get; set; }
        public string gender { get; set; }
        public Nullable<int> SecurityGroupId { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<int> Update_By { get; set; }
    }
}
