//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rebate_Details
    {
        public int R_ID { get; set; }
        public Nullable<int> Reg_ID { get; set; }
        public Nullable<int> Society_ID { get; set; }
        public Nullable<int> Project_ID { get; set; }
        public Nullable<decimal> Rebate { get; set; }
        public string Flex_1 { get; set; }
        public string Flex_2 { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_ON { get; set; }
        public string Updated_By { get; set; }
        public string Updated_On { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
