//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resale_Form
    {
        public int ID { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StaffName { get; set; }
        public string Designation { get; set; }
        public string StaffOffice { get; set; }
        public string DealFileDetails { get; set; }
        public string BuyerName { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> TotalDealsAmount { get; set; }
        public Nullable<decimal> StaffShare { get; set; }
        public Nullable<decimal> OfficeShare { get; set; }
        public Nullable<decimal> StaffAmount { get; set; }
        public Nullable<decimal> OfficeAmount { get; set; }
        public string Remarks { get; set; }
        public string Flex_1 { get; set; }
        public string Flex_2 { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public string SellerName { get; set; }
    }
}
