//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInstallment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleInstallment()
        {
            this.PaymentInstallments = new HashSet<PaymentInstallment>();
        }
    
        public int Ins_ID { get; set; }
        public Nullable<int> Booking_ID { get; set; }
        public Nullable<int> Unit_ID { get; set; }
        public Nullable<int> Project_ID { get; set; }
        public string ins_milestone { get; set; }
        public Nullable<double> ins_milestone_percentage { get; set; }
        public Nullable<double> ins_amount { get; set; }
        public Nullable<double> ins_amount_tax { get; set; }
        public Nullable<double> ins_latesurcharge_amount { get; set; }
        public Nullable<double> ins_total_amount { get; set; }
        public string ins_due_date { get; set; }
        public string ins_payment_status { get; set; }
        public Nullable<double> ins_remaining { get; set; }
        public Nullable<double> ins_balance { get; set; }
        public Nullable<System.DateTime> Created_ON { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public Nullable<int> SecurityGroupId { get; set; }
        public Nullable<decimal> OtherTaxAmount { get; set; }
        public Nullable<int> Payment_Account { get; set; }
        public Nullable<bool> AuthorizeStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentInstallment> PaymentInstallments { get; set; }
        public virtual PropertySale PropertySale { get; set; }
    }
}
