//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_Template
    {
        public int ID { get; set; }
        public string Template_Code { get; set; }
        public string Tempalte_Name { get; set; }
        public string Template_Text { get; set; }
        public Nullable<System.DateTime> Template_Date { get; set; }
        public string Flex_1 { get; set; }
        public string Flex_2 { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public string Updated_By { get; set; }
        public Nullable<int> SecurityGroupId { get; set; }
    }
}
